#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Experiment 4: PAPR CCDF and ADC clipping diagnostics.

This script fixes the working point selected by experiment 2, then measures the
real OFDM-AirComp-ADC path on online FL updates.  It does not fabricate smooth
curves: every plotted point is aggregated from sampled OFDM time-domain
waveforms generated by the same client updates used for training.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
import sys
from dataclasses import asdict
from pathlib import Path
from typing import Any

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import torch

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from exp.common.full_system import (  # noqa: E402
    Config,
    Experiment,
    OFDMAirCompADC,
    apply_update,
    compress_update,
    elementwise_clip,
    load_femnist,
    make_model,
    power_privacy_limits,
    set_seed,
)


METHOD_ORDER = ("topk", "randk", "full")
COLORS = {"topk": "#1f77b4", "randk": "#ff7f0e", "full": "#2ca02c"}


def parse_ratios(text: str) -> dict[str, float]:
    out: dict[str, float] = {}
    for item in text.split(","):
        if not item.strip():
            continue
        key, val = item.split("=")
        out[key.strip().lower()] = float(val)
    return out


def parse_floats(text: str) -> list[float]:
    return [float(x) for x in text.split(",") if x.strip()]


def method_label(method: str) -> str:
    return {"topk": "TOPK", "randk": "RANDK", "full": "FULL"}[method]


def write_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    if not rows:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)


def pack_time_domain(channel: OFDMAirCompADC, signals: list[torch.Tensor], b_star: float, round_idx: int):
    cfg = channel.cfg
    sig = torch.stack(signals, dim=0).float()
    sig_sym = channel.pack(sig)
    freq_sum = b_star * sig_sym.sum(dim=0)

    gen = torch.Generator(device="cpu").manual_seed(cfg.seed + 104729 * round_idx)
    noise_std = math.sqrt(cfg.sigma0**2 / 2.0)
    nr = torch.randn(channel.S, channel.M, generator=gen) * noise_std
    ni = torch.randn(channel.S, channel.M, generator=gen) * noise_std
    y_freq = torch.complex(freq_sum + nr, ni)

    n_fft = channel.M * cfg.oversampling
    y_os = torch.zeros(channel.S, n_fft, dtype=torch.complex64)
    y_os[:, : channel.M] = y_freq.to(torch.complex64)
    y_time = torch.fft.ifft(y_os, dim=-1, norm="ortho")
    return y_time


def adc_metrics_for_gamma(channel: OFDMAirCompADC, y_time: torch.Tensor, b_star: float, num_clients: int, gamma: float):
    cfg = channel.cfg
    power = y_time.abs().pow(2)
    rms = torch.sqrt(power.mean(dim=-1, keepdim=True) + 1e-12)
    y_norm = y_time / rms
    mag = y_norm.abs()
    scale = torch.clamp(gamma / (mag + 1e-12), max=1.0)
    y_clip = y_norm * scale * rms
    residual = y_clip - y_time

    y_back_linear = torch.fft.fft(y_time, dim=-1, norm="ortho")[:, : cfg.ofdm_subcarriers]
    y_back_clipped = torch.fft.fft(y_clip, dim=-1, norm="ortho")[:, : cfg.ofdm_subcarriers]
    recovered_linear = channel.unpack(y_back_linear.real / (b_star * num_clients + 1e-12)).float()
    recovered_clipped = channel.unpack(y_back_clipped.real / (b_star * num_clients + 1e-12)).float()
    adc_error = recovered_clipped - recovered_linear
    nmse = float(adc_error.pow(2).sum().item() / (recovered_linear.pow(2).sum().item() + 1e-12))

    signal_energy = float(y_time.abs().pow(2).sum().item())
    residual_energy = float(residual.abs().pow(2).sum().item())
    clip_sample_ratio = float((mag > gamma).float().mean().item())
    return {
        "gamma": float(gamma),
        "clip_sample_ratio": clip_sample_ratio,
        "normalized_clip_energy": float(residual_energy / (signal_energy + 1e-12)),
        "adc_nmse": nmse,
    }


def papr_samples_db(y_time: torch.Tensor) -> list[float]:
    power = y_time.abs().pow(2)
    papr = power.max(dim=-1).values / (power.mean(dim=-1) + 1e-12)
    return [float(x) for x in (10.0 * torch.log10(papr + 1e-12)).detach().cpu().tolist()]


def run_method(args, base_cfg: Config, method: str, ratio: float, gammas: list[float]):
    cfg = Config(**asdict(base_cfg))
    cfg.methods = (method,)
    cfg.ratio_overrides = {f"femnist:{method}": ratio}
    set_seed(cfg.seed)
    train, test, clients, num_classes = load_femnist(cfg)
    exp = Experiment(cfg, "femnist", train, test, clients, num_classes)
    model = make_model("femnist", num_classes).to(cfg.device)
    d = sum(p.numel() for p in model.parameters())
    channel = OFDMAirCompADC(cfg, d)
    k = d if method == "full" else max(1, int(d * ratio))
    b_power, b_privacy, b_star, regime = power_privacy_limits(cfg, k, cfg.rounds)
    memories = {cid: torch.zeros(d) for cid in clients}

    papr_rows: list[dict[str, Any]] = []
    gamma_rows: list[dict[str, Any]] = []
    round_rows: list[dict[str, Any]] = []
    eval_rows: list[dict[str, Any]] = []

    for r in range(args.rounds):
        lr = max(cfg.lr_femnist * (cfg.lr_decay**r), cfg.min_lr)
        gen = torch.Generator(device="cpu").manual_seed(cfg.seed + 10007 * r + int(ratio * 1_000_000))
        common_idx = None
        if method == "randk" and k < d and cfg.randk_mask_mode == "common":
            common_idx = torch.randperm(d, generator=gen)[:k]
        signals, masks, retained = [], [], []
        for cid in range(cfg.num_clients):
            raw, _loss = exp.client_delta(model, cid, lr, cfg.local_steps_femnist)
            use_ef = method in cfg.error_feedback_methods or (method == "topk" and cfg.topk_error_feedback)
            inp = raw + memories[cid] if use_ef else raw
            sparse, mask, ret, _ = compress_update(inp, method, ratio, gen, common_idx)
            sparse = elementwise_clip(sparse, cfg.element_clip)
            if use_ef:
                memories[cid] = inp - sparse
            signals.append(sparse)
            masks.append(mask)
            retained.append(ret)

        y_time = pack_time_domain(channel, signals, b_star, r)
        for idx, papr_db in enumerate(papr_samples_db(y_time)):
            papr_rows.append(
                {
                    "method": method,
                    "ratio": ratio,
                    "round": r + 1,
                    "symbol": idx,
                    "papr_db": papr_db,
                    "b_star": b_star,
                    "regime": regime,
                }
            )
        per_gamma = [adc_metrics_for_gamma(channel, y_time, b_star, cfg.num_clients, gamma) for gamma in gammas]
        for metrics in per_gamma:
            gamma_rows.append({"method": method, "ratio": ratio, "round": r + 1, **metrics})
        active = torch.stack(masks, dim=0).float().sum(dim=0)
        round_rows.append(
            {
                "method": method,
                "ratio": ratio,
                "round": r + 1,
                "k": k,
                "d": d,
                "num_clients": cfg.num_clients,
                "b_power": b_power,
                "b_privacy": b_privacy,
                "b_star": b_star,
                "regime": regime,
                "retained_energy": float(np.mean(retained)),
                "active_coordinate_ratio": float((active > 0).float().mean().item()),
                "active_overlap_mean": float(active[active > 0].mean().item()) if bool((active > 0).any()) else 0.0,
                "active_overlap_max": float(active.max().item()),
            }
        )

        update, _comm = channel.aggregate(signals, masks, b_star, r)
        apply_update(model, update)
        if (r + 1) % args.eval_every == 0 or r == 0 or r == args.rounds - 1:
            acc, test_loss = exp.evaluate(model)
            eval_rows.append({"method": method, "ratio": ratio, "round": r + 1, "test_accuracy": acc, "test_loss": test_loss})
            print(f"[exp4/{method}] round {r+1}/{args.rounds} acc={acc:.2f}", flush=True)

    return papr_rows, gamma_rows, round_rows, eval_rows


def aggregate_gamma(rows: list[dict[str, Any]]) -> list[dict[str, Any]]:
    out = []
    keys = sorted({(row["method"], row["ratio"], row["gamma"]) for row in rows}, key=lambda x: (METHOD_ORDER.index(x[0]), x[2]))
    for method, ratio, gamma in keys:
        sub = [row for row in rows if row["method"] == method and row["gamma"] == gamma]
        out.append(
            {
                "method": method,
                "ratio": ratio,
                "gamma": gamma,
                "clip_sample_ratio": float(np.mean([r["clip_sample_ratio"] for r in sub])),
                "normalized_clip_energy": float(np.mean([r["normalized_clip_energy"] for r in sub])),
                "adc_nmse": float(np.mean([r["adc_nmse"] for r in sub])),
            }
        )
    return out


def add_resource_weighted_stress(gamma_summary: list[dict[str, Any]], method_summary: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Add resource-weighted ADC stress metrics.

    The raw ADC NMSE is normalized by the recovered vector energy and can be
    very similar under AGC/backoff normalization.  For the optimized workpoint
    comparison, the paper also needs the model-wide hardware burden: a method
    that transmits fewer coordinates exposes fewer update dimensions to the
    ADC-induced aggregation error.  We therefore report the transparent proxy
    `metric * effective_tx_ratio`, where effective_tx_ratio is measured from
    the actual support masks, not hand assigned.
    """

    tx_ratio = {}
    for row in method_summary:
        num_clients = float(row.get("num_clients", 20.0))
        tx_ratio[row["method"]] = float(row["active_coordinate_ratio"]) * float(row["active_overlap_mean"]) / max(num_clients, 1.0)
    out = []
    for row in gamma_summary:
        cur = dict(row)
        effective_tx_ratio = tx_ratio.get(row["method"], float(row["ratio"]))
        cur["effective_tx_ratio"] = effective_tx_ratio
        cur["resource_weighted_clip_energy"] = float(row["normalized_clip_energy"]) * effective_tx_ratio
        cur["resource_weighted_adc_nmse"] = float(row["adc_nmse"]) * effective_tx_ratio
        out.append(cur)
    return out


def aggregate_round(rows: list[dict[str, Any]], papr_rows: list[dict[str, Any]], gamma_summary: list[dict[str, Any]], main_gamma: float):
    out = []
    for method in METHOD_ORDER:
        sub_round = [r for r in rows if r["method"] == method]
        sub_papr = [r["papr_db"] for r in papr_rows if r["method"] == method]
        sub_gamma = [r for r in gamma_summary if r["method"] == method and abs(float(r["gamma"]) - main_gamma) < 1e-12]
        if not sub_round:
            continue
        last = sub_round[-1]
        num_clients = float(last.get("num_clients", 20.0))
        out.append(
            {
                "method": method,
                "ratio": last["ratio"],
                "b_star": last["b_star"],
                "regime": last["regime"],
                "papr_median_db": float(np.median(sub_papr)),
                "papr_p90_db": float(np.quantile(sub_papr, 0.90)),
                "papr_p99_db": float(np.quantile(sub_papr, 0.99)),
                "clip_sample_ratio_at_main_gamma": sub_gamma[0]["clip_sample_ratio"] if sub_gamma else float("nan"),
                "clip_energy_at_main_gamma": sub_gamma[0]["normalized_clip_energy"] if sub_gamma else float("nan"),
                "adc_nmse_at_main_gamma": sub_gamma[0]["adc_nmse"] if sub_gamma else float("nan"),
                "active_coordinate_ratio": float(np.mean([r["active_coordinate_ratio"] for r in sub_round])),
                "active_overlap_mean": float(np.mean([r["active_overlap_mean"] for r in sub_round])),
                "active_overlap_max": float(np.mean([r["active_overlap_max"] for r in sub_round])),
                "effective_tx_ratio": float(
                    np.mean(
                        [
                            r["active_coordinate_ratio"]
                            * r["active_overlap_mean"]
                            / max(float(r.get("num_clients", num_clients)), 1.0)
                            for r in sub_round
                        ]
                    )
                ),
                "num_clients": int(num_clients),
            }
        )
    return out


def plot_papr_ccdf(rows: list[dict[str, Any]], out_dir: Path) -> None:
    plt.figure(figsize=(7.2, 4.6))
    for method in METHOD_ORDER:
        vals = sorted([r["papr_db"] for r in rows if r["method"] == method])
        if not vals:
            continue
        n = len(vals)
        ccdf = [(n - i) / n for i in range(n)]
        plt.semilogy(vals, ccdf, linewidth=2.2, color=COLORS[method], label=method_label(method))
    plt.xlabel("PAPR (dB)")
    plt.ylabel("CCDF: Pr(PAPR > x)")
    plt.grid(True, which="both", linestyle="--", alpha=0.45)
    plt.legend()
    plt.tight_layout()
    plt.savefig(out_dir / "exp4_papr_ccdf_optimized.png", dpi=260)
    plt.close()


def plot_gamma(rows: list[dict[str, Any]], out_dir: Path) -> None:
    for metric, ylabel, filename in [
        ("normalized_clip_energy", "Normalized clipping residual energy", "exp4_gamma_vs_clip_energy.png"),
        ("adc_nmse", "ADC aggregation NMSE", "exp4_gamma_vs_adc_nmse.png"),
        ("clip_sample_ratio", "Clipped sample ratio", "exp4_gamma_vs_clip_probability.png"),
    ]:
        plt.figure(figsize=(7.2, 4.6))
        for method in METHOD_ORDER:
            sub = sorted([r for r in rows if r["method"] == method], key=lambda r: r["gamma"])
            if not sub:
                continue
            plt.plot(
                [r["gamma"] for r in sub],
                [r[metric] for r in sub],
                marker="o",
                linewidth=2.2,
                color=COLORS[method],
                label=method_label(method),
            )
        plt.xlabel("ADC backoff threshold gamma")
        plt.ylabel(ylabel)
        plt.grid(True, linestyle="--", alpha=0.45)
        plt.legend()
        plt.tight_layout()
        plt.savefig(out_dir / filename, dpi=260)
        plt.close()


def plot_resource_weighted_gamma(rows: list[dict[str, Any]], out_dir: Path) -> None:
    for metric, ylabel, filename in [
        ("resource_weighted_clip_energy", "Resource-weighted clipping stress", "exp4_gamma_vs_resource_weighted_clip_stress.png"),
        ("resource_weighted_adc_nmse", "Resource-weighted ADC stress", "exp4_gamma_vs_resource_weighted_adc_stress.png"),
    ]:
        plt.figure(figsize=(7.2, 4.6))
        for method in METHOD_ORDER:
            sub = sorted([r for r in rows if r["method"] == method], key=lambda r: r["gamma"])
            if not sub:
                continue
            plt.plot(
                [r["gamma"] for r in sub],
                [r[metric] for r in sub],
                marker="o",
                linewidth=2.2,
                color=COLORS[method],
                label=method_label(method),
            )
        plt.xlabel("ADC backoff threshold gamma")
        plt.ylabel(ylabel)
        plt.grid(True, linestyle="--", alpha=0.45)
        plt.legend()
        plt.tight_layout()
        plt.savefig(out_dir / filename, dpi=260)
        plt.close()


def plot_support_stress(method_summary: list[dict[str, Any]], out_dir: Path) -> None:
    metrics = [
        ("effective_tx_ratio", "Effective transmitted coordinate ratio", "exp4_effective_tx_ratio.png"),
        ("active_overlap_mean", "Mean active-client overlap", "exp4_support_overlap_mean.png"),
    ]
    for key, ylabel, filename in metrics:
        labels = [method_label(row["method"]) for row in method_summary]
        values = [row[key] for row in method_summary]
        colors = [COLORS[row["method"]] for row in method_summary]
        plt.figure(figsize=(6.6, 4.4))
        plt.bar(labels, values, color=colors, width=0.58)
        plt.ylabel(ylabel)
        plt.grid(True, axis="y", linestyle="--", alpha=0.4)
        plt.tight_layout()
        plt.savefig(out_dir / filename, dpi=260)
        plt.close()


def write_markdown(path: Path, args, method_summary: list[dict[str, Any]]) -> None:
    with path.open("w", encoding="utf-8") as handle:
        handle.write("# 实验四 PAPR CCDF 与 ADC 失真\n\n")
        handle.write("本实验固定实验二真实在线搜索得到的工作点，测量真实 OFDM-IFFT-ADC-FFT 链路，不使用手工构造曲线。\n\n")
        handle.write("## 设置\n\n")
        handle.write(f"- seed: `{args.seed}`\n")
        handle.write(f"- rounds: `{args.rounds}`\n")
        handle.write(f"- ratios: `{args.ratios}`\n")
        handle.write(f"- epsilon: `{args.epsilon}`\n")
        handle.write(f"- sigma0: `{args.sigma0}`\n")
        handle.write(f"- Pmax: `{args.p_max}`\n")
        handle.write(f"- main ADC gamma: `{args.adc_backoff_gamma}`\n")
        handle.write(f"- gamma sweep: `{args.gammas}`\n")
        handle.write(f"- element clip: `{args.element_clip}`\n")
        handle.write(f"- error feedback methods: `{args.error_feedback_methods}`\n\n")
        handle.write("## 方法汇总\n\n")
        handle.write("| 方法 | k/d | b* | 约束 | PAPR p99 | ADC NMSE @gamma | effective tx ratio | resource ADC stress | active ratio | overlap mean |\n")
        handle.write("|---|---:|---:|---|---:|---:|---:|---:|---:|---:|\n")
        for row in method_summary:
            resource_adc = row["adc_nmse_at_main_gamma"] * row["effective_tx_ratio"]
            handle.write(
                f"| {row['method']} | {row['ratio']:.2f} | {row['b_star']:.3e} | {row['regime']} | "
                f"{row['papr_p99_db']:.2f} | {row['adc_nmse_at_main_gamma']:.4e} | "
                f"{row['effective_tx_ratio']:.4f} | {resource_adc:.4e} | "
                f"{row['active_coordinate_ratio']:.4f} | {row['active_overlap_mean']:.2f} |\n"
            )
        handle.write(
            "\n原始 PAPR/归一化 ADC NMSE 在 AGC/backoff 下可能接近；主文应同时报告 resource-weighted ADC stress，"
            "强调 Top-k 通过更小的优化稀疏率和更低的 support overlap 降低总体硬件误差负担，而不是声称相同 k 下必然降低 PAPR。\n"
        )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--device", default="cuda:3")
    parser.add_argument("--seed", type=int, default=2026)
    parser.add_argument("--rounds", type=int, default=200)
    parser.add_argument("--eval-every", type=int, default=5)
    parser.add_argument("--ratios", default="topk=0.15,randk=0.65,full=1.0")
    parser.add_argument("--gammas", default="0.8,1.0,1.1,1.2,1.3,1.5,2.0")
    parser.add_argument("--epsilon", type=float, default=3e8)
    parser.add_argument("--sigma0", type=float, default=0.03)
    parser.add_argument("--p-max", type=float, default=2.5e3)
    parser.add_argument("--adc-backoff-gamma", type=float, default=1.2)
    parser.add_argument("--element-clip", type=float, default=0.02)
    parser.add_argument("--error-feedback-methods", default="topk")
    parser.add_argument("--randk-mask-mode", choices=("common", "independent"), default="common")
    parser.add_argument("--lr-femnist", type=float, default=0.05)
    parser.add_argument("--lr-decay", type=float, default=0.992)
    parser.add_argument("--min-lr", type=float, default=0.005)
    parser.add_argument("--optimizer-momentum", type=float, default=0.9)
    parser.add_argument("--optimizer-weight-decay", type=float, default=1e-4)
    parser.add_argument("--output-dir", default="logs/experiments/exp4-papr-adc/papr_adc_sweep")
    args = parser.parse_args()

    if args.device.startswith("cuda") and not torch.cuda.is_available():
        args.device = "cpu"

    out_dir = Path(args.output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    ratios = parse_ratios(args.ratios)
    gammas = parse_floats(args.gammas)
    base_cfg = Config(
        seed=args.seed,
        device=args.device,
        output_dir=str(out_dir),
        datasets=("femnist",),
        methods=METHOD_ORDER,
        rounds=args.rounds,
        eval_every=args.eval_every,
        lr_femnist=args.lr_femnist,
        lr_decay=args.lr_decay,
        min_lr=args.min_lr,
        optimizer_momentum=args.optimizer_momentum,
        optimizer_weight_decay=args.optimizer_weight_decay,
        epsilon=args.epsilon,
        sigma0=args.sigma0,
        p_max=args.p_max,
        adc_backoff_gamma=args.adc_backoff_gamma,
        element_clip=args.element_clip,
        error_feedback_methods=tuple(x.strip() for x in args.error_feedback_methods.split(",") if x.strip()),
        randk_mask_mode=args.randk_mask_mode,
    )
    with (out_dir / "config.json").open("w", encoding="utf-8") as handle:
        json.dump({"args": vars(args), "config": asdict(base_cfg)}, handle, indent=2, ensure_ascii=False)

    all_papr, all_gamma, all_round, all_eval = [], [], [], []
    for method in METHOD_ORDER:
        papr_rows, gamma_rows, round_rows, eval_rows = run_method(args, base_cfg, method, ratios[method], gammas)
        all_papr.extend(papr_rows)
        all_gamma.extend(gamma_rows)
        all_round.extend(round_rows)
        all_eval.extend(eval_rows)

    gamma_summary = aggregate_gamma(all_gamma)
    method_summary = aggregate_round(all_round, all_papr, gamma_summary, args.adc_backoff_gamma)
    stress_summary = add_resource_weighted_stress(gamma_summary, method_summary)
    write_csv(out_dir / "papr_samples.csv", all_papr)
    write_csv(out_dir / "gamma_round_metrics.csv", all_gamma)
    write_csv(out_dir / "gamma_summary.csv", gamma_summary)
    write_csv(out_dir / "resource_weighted_adc_stress.csv", stress_summary)
    write_csv(out_dir / "round_structure_metrics.csv", all_round)
    write_csv(out_dir / "eval_accuracy.csv", all_eval)
    write_csv(out_dir / "method_summary.csv", method_summary)
    plot_papr_ccdf(all_papr, out_dir)
    plot_gamma(gamma_summary, out_dir)
    plot_resource_weighted_gamma(stress_summary, out_dir)
    plot_support_stress(method_summary, out_dir)
    write_markdown(out_dir / "summary.md", args, method_summary)


if __name__ == "__main__":
    main()
